### ISSUE TITLE
[Playwright] check-tests doesn't create titles from test.describe.parallel

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/check-tests#113]
Source code example Playwrigh typescript:

![image_1jwr6va](https://github.com/testomatio/check-tests/assets/77803888/d5e86252-0a9d-4ede-a6d4-cb146bff8ca2)

Testomat shows:

![image_7azmu4](https://github.com/testomatio/check-tests/assets/77803888/b56a3a81-58fb-46a4-b60f-c326c355d105)

**Comment by mykhailiukVitalii** [comment]
PR - https://github.com/testomatio/check-tests/pull/115
I have fixed this issue by expanding "describe" by "parallel" option.
But, in my case, script `"test": "mocha tests/**_test.js -R ./node_modules/@testomatio/reporter/lib/adapter/mocha.js"` doesn't work and I couldn't test all the tests. @DavertMik FYI
Because I added tests for the playwright adapter, but can't check it!

**Comment by mykhailiukVitalii** [comment]
Fix included to the latest beta version = 0.8.17-beta-3

Test evidences:


![Image](https://github.com/testomatio/check-tests/assets/82405549/1ab9f239-9c6d-47f5-95ac-b664d61353e0)



![Image](https://github.com/testomatio/check-tests/assets/82405549/793e9229-10bf-4369-95b4-336ee760281d)
