### ISSUE TITLE
[Playwright/Typescript] Unhandled exception on import skipped describes

### ISSUE THREAD

**Issue by sttaran** [testomatio/check-tests#82]
When I have skipped describes, I get an error like on the screenshot. "Skip" at the test level works properly
```ts
test.describe.skip('Email notifications', () => {
	test.describe('Some', () => {
```
<img width="1521" alt="Screenshot 2023-04-01 at 13 28 59" src="https://user-images.githubusercontent.com/53534240/229281189-47d798a6-a09e-4b54-b1a3-2d5a16f41750.png">

**Comment by mykhailiukVitalii** [comment]
@poliarush I have added unit test for the test.describe.skip, test.skip, test.describe.fixme cases

**Comment by poliarush** [comment]
@mykhailiukVitalii please publish beta version to user to test it

**Comment by mykhailiukVitalii** [comment]
The fix is already included in the latest stable version of check-tests@latest. Checked locally - everything works. So I'm closing this issue.
Some results: 
![Screenshot-1](https://user-images.githubusercontent.com/82405549/236634029-469536c3-7f04-484d-b043-3bfa68b1fe43.png)
![Screenshot-2-skip](https://user-images.githubusercontent.com/82405549/236634034-f9987828-03ed-4d82-b51c-96059e350562.png)
